# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# See params.pp in each class for what options are available

---
certs:
  group: vagrant
  deploy: true
  generate: true
katello_devel:
  deployment_dir: /home/vagrant
  user: vagrant
  rvm: true
  db_type: postgres
capsule:
  register_in_foreman: true
  pulp_master: true
  puppet: true
  templates: false
foreman_proxy:
  custom_repo: true
  http: true
  ssl_port: '9090'
  templates: true
  ssl_ca: /etc/foreman-proxy/ssl_ca.pem
  ssl_cert: /etc/foreman-proxy/ssl_cert.pem
  ssl_key: /etc/foreman-proxy/ssl_key.pem
  foreman_ssl_ca: /etc/foreman-proxy/foreman_ssl_ca.pem
  foreman_ssl_cert: /etc/foreman-proxy/foreman_ssl_cert.pem
  foreman_ssl_key: /etc/foreman-proxy/foreman_ssl_key.pem
  pulp_master: true
  puppet: true
  tftp: true
  puppetca: true
  tftp_syslinux_root:
  tftp_syslinux_files:
  tftp_root: /var/lib/tftpboot
  tftp_dirs:
    - /var/lib/tftpboot/pxelinux.cfg
    - /var/lib/tftpboot/boot
  http_port: "8000"
"foreman_proxy::plugin::pulp":
"katello_devel::plugin::gutterball": true
"katello_devel::plugin::foreman_gutterball": true
"foreman::plugin::fusor": true
